# -*- coding: utf-8 -*-
"""Grain-size_predictior_using_SEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qDtKcMUNj-3n0VOTYVruhRKCSgD8ws8
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

import os
import pandas as pd

excel_path = "/content/Results.xlsx"
images_dir = "/content/sem_images"

# 1. Check Excel file and sheets
xls = pd.ExcelFile(excel_path)
print("Sheet names in Excel:")
print(xls.sheet_names)

print("\n---\n")

# 2. Check images folder
print("Images directory exists?", os.path.exists(images_dir))
print("Files in images_dir:")
print(os.listdir(images_dir))

sheet_to_check = xls.sheet_names[0]  # or "3" or "Bi-0.02" etc

print("Checking sheet:", sheet_to_check)

df_sample = pd.read_excel(excel_path, sheet_name=sheet_to_check)
print("\nColumns in this sheet:")
print(df_sample.columns)

print("\nFirst 5 rows:")
print(df_sample.head())

# Clean column names and check again
df_sample.columns = [str(c).strip() for c in df_sample.columns]
print("\nCleaned column names:")
print(df_sample.columns)

if "Length" in df_sample.columns:
    print("\nMean Length for this sheet:", df_sample["Length"].mean())
else:
    print("\n❌ 'Length' column not found after cleaning.")

print("Testing filename matching logic...\n")

for sheet in xls.sheet_names:
    sample_id = (str(sheet).strip().split("_")[-1])
    print(f"Sheet: '{sheet}'  -> sample_id used for matching: '{sample_id}'")

    # list images that start with that sample_id + "_"
    matched = []
    for fname in os.listdir(images_dir):
        if fname.lower().endswith((".tif", ".tiff", ".png", ".jpg", ".jpeg")):
            if fname.startswith(sample_id + "_"):
                matched.append(fname)

    print("  Matched images:", matched)
    print("  Count:", len(matched))
    print("---")